### ISSUE TITLE
dio ^5.0.0, curl_logger_dio_interceptor >=0.0.3 is forbidden.

### ISSUE THREAD

**Issue by justinelock** [OwnWeb/curl_logger_dio_interceptor#3]
i try to update dio to 5.0.0 and got this:
Because curl_logger_dio_interceptor >=0.0.3 depends on dio ^4.0.4 and 'PROJECT_NAME' depends on dio ^5.0.0, curl_logger_dio_interceptor >=0.0.3 is forbidden.
So, because 'PROJECT_NAME' depends on curl_logger_dio_interceptor ^0.0.3, version solving failed.
pub get failed (1; So, because 'PROJECT_NAME' depends on curl_logger_dio_interceptor ^0.0.3, version solving failed.)

ERROR HERE：
dio.interceptors.add(CurlLoggerDioInterceptor(printOnSuccess: true));

**Comment by Vofchuk** [comment]
Im having the same issue

**Comment by LastxTemplar** [comment]
I've forked this project and updated it, you can try it out if you want [dio_intercept_to_curl](https://pub.dev/packages/dio_intercept_to_curl)

**Comment by justinelock** [comment]
//dio.interceptors.add(CurlLoggerDioInterceptor(printOnSuccess: true));
dio.interceptors.add(DioInterceptToCurl(printOnSuccess: true));  --------- change to this , right?

**Comment by LastxTemplar** [comment]
Yes, and obviously change in pubspec to the new repo :)
